### PR TITLE
Some bug fixes and changes

### LINKED ISSUE #43: [Bug Report] it doesn't recognize ctrl+q or ctrl+w to exit (completely colse) the application
open walc
and when you want to close it, you must close it from the top bar (through Windows -> Exit)

it'll be very nice to enable exiting when clicking ctrl+q or ctrl+w.

My OS: Ubuntu 20.04

thanks :innocent: :innocent:

### PR DESCRIPTION
**Pull request by Zzombiee2361**
- Removed waStore since window.Store is already loaded by whatsapp-web.js
- Removed dark mode toggle since whatsapp officially supports it
- Better window.Store detection on preload.js
- Added Ctrl+Q shortcut to exit WALC (fixes #43)
- Immediately retry connecting to whatsapp when internet is online

### CODE REVIEW

**Comment by Zzombiee2361** [comment]
@cstayyab how do I make releases? Do I just upload the AppImage file? What's latest-linux.yml for? What about snap? Any better way to contact you other than github mentions?

**Comment by cstayyab** [comment]
> how do I make releases?
I would like to work on releases myself.

> Any better way to contact you other than github mentions?
You can contact me on my email address, you will find it on my profile.

**Comment by Zzombiee2361** [comment]
Alright then, but make sure to check the library inside AppImage like mentioned here https://github.com/cstayyab/WALC/issues/42#issuecomment-671011663. It causes a lot of issues.

Please release a new version soon, I already put the changes and bumped the version.

**Comment by cstayyab** [comment]
The issues caused by that library will not be addressed in release 0.1.11. I have release 0.1.11 version and starting working on that issue. I hope it will be fixed in release 0.1.12.

**Comment by Zzombiee2361** [comment]
What do you mean? What needs to be fixed? When I built the AppImage myself it's fine, all libraries inside is normal. No zero sized library.

**Comment by cstayyab** [comment]
The issues exist for Manjaro and Arch based systems. I will have to verify WALC on different linux distros. I will be going for Manjaro first.

**Comment by cstayyab** [comment]
I will get back to you with more research.

**Comment by Zzombiee2361** [comment]
But it also happens on Ubuntu as well. You made sure that the libraries inside AppImage files aren't zero sized? I'm 100% sure that's the issue.

**Pull request merged**
