### PR TITLE
Code refactor, dashboard window, switch to vue pages, and more

### PR DESCRIPTION
**Pull request by Zzombiee2361**
## Code refactor
Huge code refactor, especially in main process. The code is now separated in `Main` folder, the old `main.js` is still being kept as `old-main.js`. Initial support for multi instance, still blocked by tray implementation. New settings system, to better categorize and better management. Unfortunately the old settings won't be compatible and will be lost, but that's more reason to visit the new Dashboard.

## Main WALC Window
Window menu are now removed and replaced with open dashboard button. New chat shortcut using `Ctrl`+`1-9`. Some background changes to support the new settings system and `InstanceManager`.

## Dashboard
A dashboard window to allow much more fine tuned interaction with the app. Currently dashboard only migrate old menu to the dashboard interface with some new additional settings, so no new shiny feature for now.

The new dashboard and offline page are using vue 2 and [vuetify](https://vuetifyjs.com). which means additional compilation process by webpack. The webpack config are managed by laravel mix, which made webpack configuration so much easier.

That's all the changes that I could describe, see the commits for more info. I'll leave the changelog and discussion closing to you, @cstayyab.

### CODE REVIEW

**Comment by Zzombiee2361** [comment]
Should the version bumped to 0.2? This is a pretty massive change.

**Comment by cstayyab** [comment]
> 
> 
> Should the version bumped to 0.2? This is a pretty massive change.

Yeah, that would be good!

**Review by cstayyab — CHANGES_REQUESTED** [review]
In Dashboard when toggling "Enable tray icon" with every toggle, the icon in tray turns to an ellipsis and when you turn it back on a new icon without removing the ellipsis is shown. Here is a screenshot:
Tray Icon Toggle Issue

Also when "Enable Tray Icon" is set to `No` then `Close To Tray` and any other related option should also be `disabled`

Can you please look into it?

**Comment by Zzombiee2361** [comment]
> In Dashboard when toggling "Enable tray icon" with every toggle, the icon in tray turns to an ellipsis and when you turn it back on a new icon without removing the ellipsis is shown

Can't reproduce, at least here in KDE Plasma. I'm using electron's standard [Tray.destroy()](https://www.electronjs.org/docs/api/tray#traydestroy) method to remove the tray. Must be some kind of bug with Gnome.

> Also when "Enable Tray Icon" is set to No then Close To Tray and any other related option should also be disabled

Yes it should, but I kinda not bothered to implement it because functionally there's no difference. I have an idea on how a setting could have a dependency, and get get the value based on the dependency and its own value, then render the setting UI automatically. That's pretty complicated though, so maybe a later update for that.

**Comment by Zzombiee2361** [comment]
Whoops, yeah I can reproduce the tray problem. KDE just hides it. This is an electron bug though, see https://github.com/electron/electron/issues/17622

**Comment by Zzombiee2361** [comment]
@cstayyab ping! Can this be merged then?

**Comment by cstayyab** [comment]
Yeah this can be merged.  I did final testing last night.

**Review by cstayyab — APPROVED** [review]

**Comment by Zzombiee2361** [comment]
Great! I hope you release it soon

**Comment by cstayyab** [comment]
> Great! I hope you release it soon

Facing build issues. Will migrate it to `electron-forge` (as it is more reliable) and then I will release.

**Pull request merged**
